config/routes.rb
Rails.application.routes.draw do

  resources :players
  resources :games
  resources :home

  root 'home#index'

  get "simulation_table" => "home#simulation_table", as: :simulation_table, :format => 'js'
  get "simulation" => "home#simulation", as: :simulation, :format => 'js'

end

app/models/game.rb
class Game < ActiveRecord::Base
	has_one :board
	has_many :matches
	has_many :players, through: :matches
	has_many :rounds
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def add_players
    params[:game][:player_ids].each do |player_id|
      @match = Match.new(game_id: @game.id, player_id: player_id)
      @match.save
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:name)
    end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <label for="game_date">Nombre</label><br>
    <%= f.text_field :name %>
  </div>
  <!-- <div class="field">
    <label for="game_players">Jugadores</label><br>
    <%= f.collection_select(:player_ids, Player.all, :id, :user_name, {:prompt => "Elegir jugadores"}, {:multiple => true}) %>
  </div> -->
  <div class="actions">
    <%= f.submit "Crear Partida" %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editar Partida</h1>

<%= render 'form' %>

<%= link_to 'Ver', @game %> |
<%= link_to 'Atrás', games_path %>

app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listando Partidas</h1>
<p>Para comenzar una partida deberás seleccionar una existente o crear una nueva</p>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.name %></td>
        <td>
          <% game.players.each do |player| %>
            <%= player.user_name %>
          <% end %>
        </td>
        <td><%= link_to 'Ver', game %></td>
        <td><%= link_to 'Editar', edit_game_path(game) %></td>
        <td><%= link_to 'Destruir', game, method: :delete, data: { confirm: 'Seguro que quieres eliminar esta partida?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva Partida', new_game_path %>

app/views/games/new.html.erb
<h1>Nueva Partida</h1>

<%= render 'form' %>

<%= link_to 'Atrás', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @game.name %>
</p>

<%= link_to 'Editar', edit_game_path(@game) %> |
<%= link_to 'Atrás', games_path %>