config/routes.rb
Rails.application.routes.draw do

  resources :players
  resources :games
  resources :home

  root 'home#index'

  get "simulation_table" => "home#simulation_table", as: :simulation_table, :format => 'js'
  get "simulation" => "home#simulation", as: :simulation, :format => 'js'

end

app/models/player.rb
class Player < ActiveRecord::Base
  include PlayersHelper
	has_many :matches
	has_many :games, through: :matches
	has_many :bets

	validates :user_name, uniqueness: true
	before_save :default_values

	def default_values
  	self.credit ||= 10000
	end

	def increase_credit
		self.credit += 10000
		self.save
	end

  def getRandomColor
    rand_num = rand(100)
    color = "verde"
    if rand_num < 49
      color = "blanco"
    elsif rand_num >= 49 && rand_num < 98
      color = "negro"
    end
    return color  
  end

  def do_bet
    rain = get_rain_forcast()
    credit_fraction_to_bet = get_credit_fraction(rain)
    bet_amount = self.credit * credit_fraction_to_bet
    self.credit *= (1 - credit_fraction_to_bet)
    self.save

    return bet_amount
  end

  def get_credit_fraction(rain)
    credit_fraction_to_bet = 0
    if self.credit == 0
      credit_fraction_to_bet = 0
    elsif self.credit <= 1000
      credit_fraction_to_bet = 1
    elsif rain
      credit_fraction_to_bet = (4 + rand(7)).to_f / 100
    else
      credit_fraction_to_bet = (8 + rand(8)).to_f / 100
    end 

    return credit_fraction_to_bet
  end

  def update_credit_after_result(bet_id,bet_result_color)
    bet = Bet.find(bet_id)
    box_color = Box.find(bet.box_id)
    
    if box_color.color == bet_result_color
      prize = bet.amount * box_color.payoff
      self.credit += prize
      self.save
    end

  end

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  # GET /players
  # GET /players.json
  def index
    @players = Player.all
  end

  # GET /players/1
  # GET /players/1.json
  def show
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url, notice: 'Player was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.require(:player).permit(:user_name, :credit)
    end
end

app/helpers/players_helper.rb
module PlayersHelper
	require 'json'

	$rain_forcast_valid = Time.now
	$is_rainning = false

	def get_rain_forcast
		now = Time.now
		if $rain_forcast_valid < now
			$is_rainning = rain_next_week()
			$rain_forcast_valid = Time.now + 60*60
		end
		return $is_rainning
	end

	def rain_next_week
		print("nononononononfdosbnofsnofsnofsnofnson")
		api_req_url = "http://api.openweathermap.org/data/2.5/forecast/daily?id=#{CITY_ID}&cnt=7&APPID=#{OPEN_WEATHER_MAP_API_KEY}"
		api_res = HTTParty.get(api_req_url)
		list = JSON.parse(api_res.to_json)
		
		list["list"].each do |day|
			day["weather"].each do |weather|
				if weather["main"] == "Rain"
					return true
				end
			end
		end
		return false
	end
end

app/views/players/_form.html.erb
<%= form_for(@player) do |f| %>
  <% if @player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% @player.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <label for="player_user_name">Nombre de usuario</label><br>
    <%= f.text_field :user_name %>
  </div>
  <% if !@player.new_record? %>
    <div class="field">
      <label for="player_credit">Credito</label><br>
      <%= f.number_field :credit %>
    </div>
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/players/edit.html.erb
<h1>Editar Jugador</h1>

<%= render 'form' %>

<%= link_to 'Ver', @player %> |
<%= link_to 'Atrás', players_path %>

app/views/players/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista de jugadores</h1>

<table>
  <thead>
    <tr>
      <th>Nombre de usuario</th>
      <th>Credito</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= player.user_name %></td>
        <td><%= player.credit %></td>
        <td><%= link_to 'Ver', player %></td>
        <td><%= link_to 'Editar', edit_player_path(player) %></td>
        <td><%= link_to 'Destruir', player, method: :delete, data: { confirm: 'Seguro que quieres eliminar?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Crear nuevo jugador', new_player_path %>

app/views/players/new.html.erb
<h1>Nuevo Jugador</h1>

<%= render 'form' %>

<%= link_to 'Back', players_path %>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User name:</strong>
  <%= @player.user_name %>
</p>

<p>
  <strong>Credit:</strong>
  <%= @player.credit %>
</p>

<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path %>